[client]
toolbarMode = "minimal"

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#f97316"
backgroundColor = "#0B0F1A"
secondaryBackgroundColor = "#0f162a"
textColor = "#f9fafb"
font = "sans serif"