[client]
toolbarMode = "minimal"

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#f97316"
backgroundColor = "#121212"
secondaryBackgroundColor = "#271e11"
textColor = "#f9fafb"
font = "sans serif"